FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
python3-pip \
python3-venv \
&& apt-get clean && rm -rf /var/lib/apt/lists/*

ADD pip_download /usr/local/bin/pip_download
