all:
ifeq ($(CI),true)
	./run
else
	@echo "*********************************************"
	@echo "*                                           *"
	@echo "*  Please run ./buildbot/pip/run if needed  *"
	@echo "*                                           *"
	@echo "*********************************************"
endif
