FROM fedora:37

RUN dnf update -y && dnf install -y \
gcc \
ghostscript \
ImageMagick \
patch \
ruby \
ruby-devel \
sqlite-devel \
wget

ARG USERNAME=redmine
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
&& useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

USER $USERNAME

WORKDIR /home/$USERNAME
RUN wget https://www.redmine.org/releases/redmine-5.0.5.tar.gz
RUN mkdir redmine
RUN tar -xvf redmine-5.0.5.tar.gz -C redmine --strip-components=1

WORKDIR /home/$USERNAME/redmine

ADD configuration.yml /home/$USERNAME/redmine/config
ADD database.yml /home/$USERNAME/redmine/config
RUN sed -i 's/default: textile/default: common_mark/' /home/$USERNAME/redmine/config/settings.yml

RUN echo "gem 'puma'" >Gemfile.local
RUN bundle config set --local path vendor/bundle
RUN bundle install --without development test

ADD 0001-remote-user.patch /home/$USERNAME/redmine
RUN patch -p0 <0001-remote-user.patch

ADD export_admin_api_key.rake /home/$USERNAME/redmine/lib/tasks

ADD init /home/$USERNAME
ADD run /home/$USERNAME
