FROM fedora:37

RUN dnf update -y && dnf install -y \
gcc \
ghostscript \
ImageMagick \
ruby \
ruby-devel \
sqlite-devel \
wget

ARG USERNAME=redmine
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
&& useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

USER $USERNAME

WORKDIR /home/$USERNAME
RUN wget https://github.com/naivesystems/redmine/archive/refs/tags/5.0.5+nsbox.20230903.tar.gz
RUN mkdir redmine
RUN tar -xvf 5.0.5+nsbox.20230903.tar.gz -C redmine --strip-components=1

WORKDIR /home/$USERNAME/redmine

ADD configuration.yml /home/$USERNAME/redmine/config
ADD database.yml /home/$USERNAME/redmine/config

RUN echo "gem 'puma'" >Gemfile.local
RUN bundle config set --local path vendor/bundle
RUN bundle install --without development test

ADD init /home/$USERNAME
ADD run /home/$USERNAME
ADD update_settings.rb /home/$USERNAME
