FROM fedora:38

RUN dnf update -y && dnf install -y \
git \
java-11-openjdk-headless \
openssh \
wget

ARG USERNAME=gerrit
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
&& useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

USER $USERNAME
WORKDIR /home/$USERNAME

RUN wget https://gerrit-releases.storage.googleapis.com/gerrit-3.8.2.war
RUN wget https://gerrit-ci.gerritforge.com/view/Plugins-stable-3.8/job/plugin-code-owners-bazel-master-stable-3.8/2/artifact/bazel-bin/plugins/code-owners/code-owners.jar

ADD init /home/$USERNAME
ADD run /home/$USERNAME
