#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

update_redirect_uris() {
    local realm="nsbox"
    local hostname="nsbox.local"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            "--hostname")
                shift
                echo "Using hostname $1 instead of $hostname"
                hostname="$1"
                ;;
            *)
                echo "Invalid option: $1" >&2
                exit 1
                ;;
        esac
        shift
    done

    cd "$HOME"
    export KEYCLOAK_HOME="$HOME/keycloak"
    export PATH="$PATH:$KEYCLOAK_HOME/bin"

    sudo update-ca-trust

    kcadm.sh config credentials --server "https://$hostname:9992/" \
        --realm master --user admin \
        --password "$(cat "$KEYCLOAK_HOME/admin_password.txt")"

    kcadm.sh update clients/"$(jq -r '.id' "$KEYCLOAK_HOME/client_secret.json")" -r "$realm" -f - <<EOF
{
  "redirectUris": [
    "https://$hostname:8443/*",
    "https://$hostname:9440/*",
    "https://$hostname:9441/*",
    "https://$hostname:9442/*",
    "https://$hostname:9443/*",
    "https://$hostname:9444/*"
  ],
  "webOrigins": ["+"]
}
EOF
}

update_redirect_uris "$@"
