#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

update_redirect_uris() {
    local realm="nsbox"
    local hostname="nsbox.internal"
    local loginDomain="login.nsbox.internal"
    local portalDomain="portal.nsbox.internal"
    local bugDomain="bug.nsbox.internal"
    local reviewDomain="review.nsbox.internal"
    local buildDomain="build.nsbox.internal"
    local mailDomain="mailpit.nsbox.internal"
    local crossDomain="x.nsbox.internal"
    local httpBindPort="9443"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            "--hostname")
                shift
                hostname="$1"
                echo "Using hostname $hostname instead of nsbox.internal"
                ;;
            "--login-domain")
                shift
                loginDomain="$1"
                echo "Using domain $loginDomain instead of login.nsbox.internal"
                ;;
            "--portal-domain")
                shift
                portalDomain="$1"
                echo "Using domain $portalDomain instead of portal.nsbox.internal"
                ;;
            "--bug-domain")
                shift
                bugDomain="$1"
                echo "Using domain $bugDomain instead of bug.nsbox.internal"
                ;;
            "--build-domain")
                shift
                buildDomain="$1"
                echo "Using domain $buildDomain instead of build.nsbox.internal"
                ;;
            "--review-domain")
                shift
                reviewDomain="$1"
                echo "Using domain $reviewDomain instead of review.nsbox.internal"
                ;;
            "--mail-domain")
                shift
                mailDomain="$1"
                echo "Using domain $mailDomain instead of mailpit.nsbox.internal"
                ;;
            "--cross-domain")
                shift
                crossDomain="$1"
                echo "Using domain $crossDomain instead of x.nsbox.internal"
                ;;
            "--http-port")
                shift
                echo "Using HTTP bind port $1 instead of $httpBindPort"
                httpBindPort="$1"
                ;;
            *)
                echo "Invalid option: $1" >&2
                exit 1
                ;;
        esac
        shift
    done

    cd "$HOME"
    export KEYCLOAK_HOME="$HOME/keycloak"
    export PATH="$PATH:$KEYCLOAK_HOME/bin"

    sudo update-ca-trust

    kcadm.sh config credentials --server "https://${loginDomain}:9992/" \
        --realm master --user admin \
        --password "$(cat "$KEYCLOAK_HOME/admin_password.txt")"

    kcadm.sh update clients/"$(jq -r '.id' "$KEYCLOAK_HOME/client_secret.json")" -r "$realm" -f - <<EOF
{
  "redirectUris": [
    "https://$loginDomain:$httpBindPort/*",
    "https://$portalDomain:$httpBindPort/*",
    "https://$bugDomain:$httpBindPort/*",
    "https://$reviewDomain:$httpBindPort/*",
    "https://$buildDomain:$httpBindPort/*",
    "https://$mailDomain:$httpBindPort/*",
    "https://$crossDomain:$httpBindPort/*"
  ],
  "webOrigins": ["+"]
}
EOF
}

update_redirect_uris "$@"
